apiVersion: v1
kind: Service
metadata:
  name: uni-resolver-web
spec:
  type: {{ .Values.service.web.type }}
  selector:
    app: uni-resolver-web
  ports:
    - protocol: TCP
      port: {{ .Values.service.web.port }}
      targetPort: 8080
